# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build a single processing log entry
#'
#' @param step    Name of the processing step
#' @param n_cells Number of cells in the object at this step
#' @param n_genes Number of genes in the object at this step
#' @param params  Named list of parameters used in this step
#'
#' @return A named list representing one log entry
#' @keywords internal
build_log_entry <- function(step, n_cells, n_genes, params) {
    .Call(`_scPassport_build_log_entry`, step, n_cells, n_genes, params)
}

#' Append a log entry to an existing processing log
#'
#' @param log       Existing processing log (a list of entries, may be empty).
#' @param new_entry A single log entry built by \code{build_log_entry}.
#'
#' @return The updated log list with \code{new_entry} appended.
#' @keywords internal
append_log_entry <- function(log, new_entry) {
    .Call(`_scPassport_append_log_entry`, log, new_entry)
}

#' Build a passport list from components
#'
#' @param object_id     Name/ID of this Seurat object
#' @param rds_self      RDS registry number of this object
#' @param animal_id     Individual animal identifier
#' @param species       Species name
#' @param sex           Sex of the animal
#' @param age           Age of the animal
#' @param condition     Experimental condition
#' @param tissue        Tissue of origin
#' @param project       Project name
#' @param researcher    Name of the researcher
#' @param date          Date of the experiment
#' @param notes         Free-text notes
#' @param parent_id     Object ID of the direct parent
#' @param rds_parent    RDS number of the parent object
#' @param lineage       Full ancestry chain as character vector
#' @param children      Object IDs of children
#' @param rds_children  RDS numbers of children objects
#' @param custom_keys   Names of custom fields
#' @param custom_vals   Values of custom fields
#'
#' @return A named list representing the passport
#' @keywords internal
build_passport <- function(object_id, rds_self, animal_id, species, sex, age, condition, tissue, project, researcher, date, notes, parent_id, rds_parent, lineage, children, rds_children, custom_keys, custom_vals) {
    .Call(`_scPassport_build_passport`, object_id, rds_self, animal_id, species, sex, age, condition, tissue, project, researcher, date, notes, parent_id, rds_parent, lineage, children, rds_children, custom_keys, custom_vals)
}

#' Check whether a passport list is valid
#'
#' @param passport A list (the \code{@misc$passport} slot of a Seurat object).
#' @return TRUE if the passport contains all required fields, FALSE otherwise.
#' @keywords internal
validate_passport <- function(passport) {
    .Call(`_scPassport_validate_passport`, passport)
}

